### PR TITLE
Fix issues in #2

### PR DESCRIPTION
**Pull request by Apceniy**
Attempt to fix build errors and resolve reviews from #2

### CODE REVIEW

**Review by l1ttleO — CHANGES_REQUESTED** [review]
Please see #2 for issues that need to be resolved

**Comment by Apceniy** [comment]
> Please see #2 for issues that need to be resolved

Why? There's old and not fully actual code.

**Comment by l1ttleO** [comment]
> > Please see #2 for issues that need to be resolved
> 
> Why? There's old and not fully actual code.

Because I can't comment on lines you didn't change in this PR

**Comment by Apceniy** [comment]
Resolved all suggested changes.

**Review by l1ttleO — APPROVED** [review]
LGTM

**Pull request merged**
